language: android
sudo: false
cache:
  directories:
    - $HOME/.m2
before_install:
  - mkdir ~/bin
  - wget https://raw.github.com/technomancy/leiningen/stable/bin/lein -P ~/bin/
  - chmod a+x ~/bin/lein
android:
  components:
    - build-tools-18.1.1
    - android-18
lein: ~/bin/lein
script:
  - lein with-profile travis droid local-test
  - lein with-profile travis coverage
